-- Complete Database Schema for POS Portal
-- Paste this entire block into the Supabase SQL Editor and hit RUN.

-- 1. Create Tables
CREATE TABLE public.profiles (
  id uuid references auth.users not null primary key,
  email text unique not null,
  role text not null default 'Cashier',
  status text not null default 'pending',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE TABLE public.products (
  sku text primary key,
  name text not null,
  category text,
  price numeric not null default 0,
  stock_quantity integer not null default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE TABLE public.accounts (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE TABLE public.sales (
  id uuid default gen_random_uuid() primary key,
  cashier_id uuid references public.profiles(id) not null,
  subtotal numeric not null,
  tax numeric not null,
  discount numeric not null,
  total numeric not null,
  payment_method text not null,
  account_id bigint references public.accounts(id), -- Only used if payment_method is UPI
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE TABLE public.sale_items (
  id uuid default gen_random_uuid() primary key,
  sale_id uuid references public.sales(id) on delete cascade not null,
  sku text references public.products(sku) not null,
  quantity integer not null,
  price_at_time numeric not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sale_items ENABLE ROW LEVEL SECURITY;

-- 3. Create RLS Policies
-- Allow anyone logged in to read profiles, products, accounts, sales
CREATE POLICY "Enable read for authenticated users" ON public.profiles FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable read for authenticated users" ON public.products FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable read for authenticated users" ON public.accounts FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable read for authenticated users" ON public.sales FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable read for authenticated users" ON public.sale_items FOR SELECT TO authenticated USING (true);

-- Allow authenticated users to insert sales and sale_items
CREATE POLICY "Enable insert for authenticated users" ON public.sales FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Enable insert for authenticated users" ON public.sale_items FOR INSERT TO authenticated WITH CHECK (true);

-- Allow Admins to manage products, accounts, and profiles
CREATE POLICY "Admins can manage products" ON public.products FOR ALL TO authenticated USING (
  (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'Admin'
);
CREATE POLICY "Admins can manage accounts" ON public.accounts FOR ALL TO authenticated USING (
  (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'Admin'
);
CREATE POLICY "Admins can update profiles" ON public.profiles FOR UPDATE TO authenticated USING (
  (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'Admin'
);

-- 4. Create Trigger to Auto-create Profiles for new Sign-ups
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, email, role, status)
  VALUES (
    NEW.id,
    NEW.email,
    -- Make ketantom@gmail.com Super Admin automatically
    CASE WHEN NEW.email = 'ketantom@gmail.com' THEN 'Admin' ELSE 'Cashier' END,
    CASE WHEN NEW.email = 'ketantom@gmail.com' THEN 'approved' ELSE 'pending' END
  );
  RETURN NEW;
END;
$$;

-- Attach trigger to auth.users
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 5. Insert dummy products for immediate testing
INSERT INTO public.products (sku, name, category, price, stock_quantity) VALUES
  ('VP-001', 'Masala Chips', 'Snacks', 25.00, 100),
  ('VP-002', 'Mango Juice 1L', 'Beverages', 85.00, 50),
  ('VP-003', 'Whole Wheat Bread', 'Bakery', 45.00, 30),
  ('VP-004', 'Dairy Milk Silk', 'Chocolates', 150.00, 40),
  ('VP-005', 'Tata Salt 1kg', 'Groceries', 28.00, 200),
  ('VP-006', 'Red Label Tea 500g', 'Groceries', 240.00, 80)
ON CONFLICT (sku) DO NOTHING;

-- 6. Insert a default UPI Account
INSERT INTO public.accounts (name) VALUES ('Default HDFC Current A/c')
ON CONFLICT DO NOTHING;
